config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  authenticated do
    root to: 'offers#index', as: :authenticated
  end
  root to: 'pages#home'
  get 'pages/privacy'
  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "registrations"  }
  resources :offers, only: [:index, :edit, :update, :show]
  resources :favorites, only: [:index], to: 'offers#favorites'
  resources :user_traits, only: [:index, :update]
  resources :profiles, only: [:show]  do
    delete "delete/:id_trait" , to: "user_traits#destroy", as: "del_trait"
  end

  # get :hellobug, to: 'pages#hellobug'
  # match "/404", :to => "errors#not_found", :via => :all
  # match "/500", :to => "errors#internal_server_error", :via => :all
  get "/404", :to => "errors#not_found"
  get "/422", :to => "errors#unacceptable"
  get "/500", :to => "errors#internal_error"



end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = current_user
    @traits = @user.user_traits
  end
end

app/views/profiles/show.html.erb
<div class="center-flex">
<div class="container">
  <div class='row'>
    <div class="col-xs-12 col-sm-3 profile-container text-center">
      <div class="color-header">
      <%= image_tag current_user.facebook_picture_url.nil? ? "#{image_path 'green-happy-face.png'}" : current_user.facebook_picture_url , class: "btn-floating btn-large profile-picture" %>
      <% if @user.first_name != nil %>
       <h3><%= @user.first_name.capitalize + " " + @user.last_name.capitalize %></h3>
      <% else %>
        <p class="font-smaller"><%= @user.email %></p>
      <% end %>
      </div>
      <% if @user.first_name != nil %>
        <label>email</label>
        <p><%= @user.email %></p>
        <label>city</label>
        <p><%= @user.location.capitalize %></p>
      <% end %>
    </div>
    <div class="col-xs-12 col-sm-8 col-sm-offset-1 profile-info profile-container">
      <div class="row">
        <div class="col-xs-12">
          <h3>My traits</h3>
          <ul>
            <% @traits.each do |trait| %>
              <li class= "label increase-margin">
                <%= trait.trait.name.upcase %>
              </li>
            <% end %>
          </ul>
          <%= link_to "Change your traits", user_traits_path, class: "btn btn-special btn-change-traits" %>
        </div>
        <div class="col-xs-12 accounts-link">
          <h3>My linked accounts</h3>
          <%= link_to '<i class="fa fa-facebook-official fa-lg" aria-hidden="true"></i>'.html_safe, user_traits_path, class: " small-tooltip", title: "facebook" %>
        </div>
        <div class="col-xs-12">
          <h3>My saved offers</h3>
          <ul>
          <% @user.offers.where( :liked? => true ).each do |offer| %>
            <li>
              <%= link_to(favorites_path, class:"deal-name") do %>
                <%= image_tag offer.deal.photo, class:"deal-photo" %>
                <%= offer.deal.name %>
                <%= link_to offer_path(offer, :liked? => false), method: :patch, class: " small-tooltip remove", title: "remove" do %>
                <i class="fa fa-trash" aria-hidden="true"></i>
                <% end %>
              <% end %>
            </li>
          <% end %>
          </ul>
        </div>
        <div class="col-xs-12">
          <h3>Already bought</h3>
          <ul>
            <% @user.offers.where( :bought? => true ).each do |offer| %>
              <li>
                <%= image_tag offer.deal.photo, class:"deal-photo" %>
                <%= offer.deal.name %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
</div>