config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  authenticated do
    root to: 'offers#index', as: :authenticated
  end
  root to: 'pages#home'
  get 'pages/privacy'
  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "registrations"  }
  resources :offers, only: [:index, :edit, :update, :show]
  resources :favorites, only: [:index], to: 'offers#favorites'
  resources :user_traits, only: [:index, :update]
  resources :profiles, only: [:show]  do
    delete "delete/:id_trait" , to: "user_traits#destroy", as: "del_trait"
  end

  # get :hellobug, to: 'pages#hellobug'
  # match "/404", :to => "errors#not_found", :via => :all
  # match "/500", :to => "errors#internal_server_error", :via => :all
  get "/404", :to => "errors#not_found"
  get "/422", :to => "errors#unacceptable"
  get "/500", :to => "errors#internal_error"



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable #request_keys: [conditions: -> { where.not(user_type: 'guest') }]
  devise :omniauthable, omniauth_providers: [:facebook]

  has_many :offers, dependent: :destroy
  has_many :deals, through: :offers
  has_many :user_traits, dependent: :destroy
  has_many :traits, through: :user_traits
  has_many :deal_tags, through: :deals
  has_many :tags, through: :deal_tags


  # validates_uniqueness_of :email, case_sensitive: false, allow_blank: false, if: :password_required?
  # validates_format_of :email, with: Devise.email_regexp, allow_blank: false, if: :password_required?
  # validates_presence_of :password, on: :create, if: :password_required?
  # validates_confirmation_of :password, :on=>:create
  # validates_length_of :password, within: Devise.password_length, if: :password_required?

  def self.find_for_facebook_oauth(auth)
    user_params = auth.to_h.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)

    user = User.where(provider: auth.provider, uid: auth.uid).first
    user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end

  private

  # def email_required?
  #   if user_type == "guest"
  #    new_record? ? false : super
  #   else
  #     true
  #   end
  # end

  # def password_required?
  #   if user_type == "guest"
  #     new_record? ? false : super
  #   else
  #     true
  #   end
  # end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info" role="alert">
    <button type="button" class="close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning" role="alert">
    <button type="button" class="close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="wrapper">
<div class="container" id="footer">
  <div class="row">
      <div class="col-xs-6">
      <%= link_to "Home", root_path %>  | <%= link_to "Privacy Policy", pages_privacy_path %>
      </div>
      <div class="col-xs-6">
        <p class="muted pull-right C">© 2016 Scout All rights reserved</p>
      </div>
    </div>
  </div>
</div>
</div>

app/views/shared/_login-modals.erb
<div id="signup" class="modal">
  <%= render 'devise/registrations/new-modal.html.erb' %>
</div>

<div id="login" class="modal">
  <%= render 'devise/sessions/new-modal.html.erb' %>
</div>

<div id="forgot" class="modal">
  <%= render 'devise/passwords/new-modal.html.erb' %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-brand" do %>
  <%= image_tag "logo.png" %>
  <% end %>

  <!-- Search form -->
<!--     <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form> -->

    <% if user_signed_in? %>

    <div class="fixed-action-btn horizontal">
      <%= image_tag current_user.facebook_picture_url.nil? ? "#{image_path 'green-happy-face.png'}" : current_user.facebook_picture_url , class: "btn-floating btn-large" %>
      <ul>
        <li class= "tooltipped" data-position = "top" data-delay = "50" data-tooltip = "<%= t('.profile', default: 'Favorites') %>" >
          <%= link_to favorites_path, class: "btn-floating waves-effect waves-light" do %>
          <i class="fa fa-heart"></i>%>
          <% end %>
        </li>
        <li class= "tooltipped" data-position = "top" data-delay = "50" data-tooltip = " <%= t(".profile", default: "Profile") %>" >
          <%= link_to profile_path(:id), class: "btn-floating"  do %>
          <i class="fa fa-user"></i>
          <% end %>
        </li>
        <li  class= "tooltipped" data-position = "top" data-delay = "50" data-tooltip = "  <%= t(".sign_out", default: "Log out") %>" >
          <%= link_to destroy_user_session_path, method: :delete, class: "btn-floating" do %>
          <i class="fa fa-sign-out"></i>
          <% end %>
        </li>
      </ul>
    </div>


  <% else %>

  <!-- Login text link -->
  <div class="login-call">
  <div class="ul list-inline">
    <li><%= link_to 'Login', '#login', { class: "home-link"} %></li>
    <li><%= link_to 'Sign Up', '#signup', { class: "home-link"} %></li>
  </div>
  </div>
  <% end %>
  </div>

app/views/shared/_traits_form.html.erb
<%= simple_form_for @user_trait, :url => user_trait_path(@user), :method => :patch do |f| %>
  <div class="traits-select">
  <%= collection_check_boxes(:user, :trait_ids, @traits, :id, :name) do |b| %>
    <%= b.label(class: "btn btn-lg waves-effect waves-light") {b.check_box(class: "hidden") + b.text} %>
  <% end %>
  </div>
  <br>
  <%= f.submit "Next", class: "btn-special waves-effect waves-light right", id: "send-traits" %>
<% end %>