config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  authenticated do
    root to: 'offers#index', as: :authenticated
  end
  root to: 'pages#home'
  get 'pages/privacy'
  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "registrations"  }
  resources :offers, only: [:index, :edit, :update, :show]
  resources :favorites, only: [:index], to: 'offers#favorites'
  resources :user_traits, only: [:index, :update]
  resources :profiles, only: [:show]  do
    delete "delete/:id_trait" , to: "user_traits#destroy", as: "del_trait"
  end

  # get :hellobug, to: 'pages#hellobug'
  # match "/404", :to => "errors#not_found", :via => :all
  # match "/500", :to => "errors#internal_server_error", :via => :all
  get "/404", :to => "errors#not_found"
  get "/422", :to => "errors#unacceptable"
  get "/500", :to => "errors#internal_error"



end

app/views/pages/_navbar.html.erb
<div class="navbar", id="home-nav">
  <!-- Logo -->
  <%= link_to "SCOUT", root_path, class: "navbar-brand brand-name" %>

    <% if user_signed_in? %>

    <div class="fixed-action-btn horizontal">
      <%= image_tag current_user.facebook_picture_url.nil? ? "#{image_path 'green-happy-face.png'}" : current_user.facebook_picture_url , class: "btn-floating btn-large" %>
      <ul>
        <li class= "tooltipped" data-position = "top" data-delay = "50" data-tooltip = "<%= t('.profile', default: 'Favorites') %>" >
          <%= link_to favorites_path, class: "btn-floating waves-effect waves-light" do %>
          <i class="fa fa-heart"></i>
          <% end %>
        </li>
        <li class= "tooltipped" data-position = "top" data-delay = "50" data-tooltip = " <%= t(".profile", default: "Profile") %>" >
          <%= link_to profile_path(:id), class: "btn-floating"  do %>
          <i class="fa fa-user"></i>
          <% end %>
        </li>
        <li  class= "tooltipped" data-position = "top" data-delay = "50" data-tooltip = "  <%= t(".sign_out", default: "Log out") %>" >
          <%= link_to destroy_user_session_path, method: :delete, class: "btn-floating" do %>
          <i class="fa fa-sign-out"></i>
          <% end %>
        </li>
      </ul>
    </div>

  <% else %>

  <!-- Login text link -->
  <div class="login-call">
  <div class="ul list-inline">
    <li><%= link_to 'Login', '#login', { class: "home-link"} %></li>
    <li><%= link_to 'Sign Up', '#signup', { class: "home-link"} %></li>
  </div>
  </div>
  <% end %>
</div>

app/views/pages/home.html.erb
<%= render 'navbar' %>
<div class="parallax-container", id="home_page_parallax">
  <div class="parallax"><img src="<%= image_path 'ski.jpg' %>"></div>
</div>
<div class="wrapper-picture">
<div class= "container">
  <div class= "row">
    <div class= "col-sm-12">
      <%= image_tag("logo.png", class: "logo-big") %>
      <h2 class="margin-less">Discover the Best Deals & Discounts</h2>
      <h5 class="padded-mini">Scout sniffs out the best deals and delivers the top 6 to you daily</h5>
 <!--      <h2><%#= t('home.heading') %></h2>
      <h3><%#= t('home.tagline') %></h3>
      <ul>
        <li><%#= t('home.bullet_1') %></li>
        <li><%#= t('home.bullet_2') %></li>
        <li><%#= t('home.bullet_3') %></li>
      </ul> -->
      <div class="row padded-small">

        <%= link_to '<i class="fa fa-facebook"></i> Sign in with Facebook'.html_safe, user_facebook_omniauth_authorize_path, {class: 'btn-facebook'} %>
      </div>
      <div class="row padded-mini">
        <%= link_to(@is_guest ? offers_path : user_traits_path , class: "email-link") do %>
        OR GET STARTED NOW <i class="fa fa-arrow-circle-right" aria-hidden="true"></i>
        <% end %>
        <%#= link_to 'Or Sign up with Email', '#signup', { class: "email-link"} %>
      </div>
      <!-- <div class="row padded-large"> -->
      <%#= link_to "Or Try Without Signing-Up", @is_guest ? offers_path : user_traits_path , class: "btn-special" %>
      <!-- </div> -->
    </div>
  </div>
</div>
</div>


<div id="signup" class="modal">
  <%= render 'devise/registrations/new-modal.html.erb' %>
</div>


<div class="container text-center padded">
  <div class="row">
    <h2>Why Us?</h2>
  </div>
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-md-3">
     <%= image_tag "save.png", class: "icon" %>
     <h5>Save Money</h5>
     <p>Get access to the best online and offline deals that are personalized to you</p>
   </div>
   <div class="col-xs-12 col-sm-6 col-md-3">
    <%= image_tag "search.png", class: "icon" %>
    <h5>Smart Matching</h5>
    <p>Scout searches the web and only matches the deals that are most relevant to your interests</p>
  </div>
  <div class="col-xs-12 col-sm-6 col-md-3">
    <%= image_tag "privacy.png", class: "icon" %>
    <h5>Privacy</h5>
    <p>You set the privacy and determine what information you want to share </p>
  </div>
  <div class="col-xs-12 col-sm-6 col-md-3">
    <%= image_tag "smart.png", class: "icon" %>
    <h5>Auto-Improve</h5>
    <p>As you provide feedback on your deals, the system will automatically improve the deals we provide</p>
  </div>
</div>
</div>

<div class="wrapper-how-works">

  <div class="container text-center padded">
    <h2>How it works</h2>
    <div class="row">
      <div class="col-xs-12 col-sm 4 col-md-4">
        <h3>Step 1</h3>
        <h5>Share with us the traits that best describe you, or import from your social accounts.</h5>
      </div>
      <div class="col-xs-12 col-sm 4 col-md-4">
        <h3>Step 2</h3>
        <h5>We'll search thousands of deals online and offline and deliver you the top 6 every day.</h5>
      </div>
      <div class="col-xs-12 col-sm 4 col-md-4">
        <h3>Step 3</h3>
        <h5>Rate the deals we've sent and we'll get smarter so you continuously get better deals</h5>
      </div>
    </div>
    <div class="row padded-small">
      <%#= link_to "Get Started Today", new_user_registration_path, {class: "btn btn-special-large"} %>
      <%= link_to 'Get Started Today', '#signup', { class: "btn btn-special-large"} %>
    </div>
  </div>
</div>

app/views/pages/privacy.html.erb
<div class="container">
<h1>Privacy Policy</h1>
 
<h3>Protecting your private information is our priority. </h3>

<p>This Statement of Privacy applies to the https://meet-scout.herokuapp.com and Scout.com and governs data collection and usage. For the purposes of this Privacy Policy, unless otherwise noted, all references to Scout.com include https://meet-scout.herokuapp.com and Scout. The Scout website is a Today's Best Deals site. By using the Scout website, you consent to the data practices described in this statement.</p>
 
<h3>Collection of your Personal Information </h3>
<p>Scout may collect personally identifiable information, such as your name. Scout may also collect anonymous demographic information, which is not unique to you, such as your age and gender. We may gather additional personal or non-personal information in the future.</p>
 
<p>Information about your computer hardware and software may be automatically collected by Scout. This information can include: your IP address, browser type, domain names, access times and referring website addresses. This information is used for the operation of the service, to maintain quality of the service, and to provide general statistics regarding use of the Scout website.</p>
 
<p>Scout encourages you to review the privacy statements of websites you choose to link to from Scout so that you can understand how those websites collect, use and share your information. Scout is not responsible for the privacy statements or other content on websites outside of the Scout website. </p>
 
<h3>Use of your Personal Information</h3>
<p>Scout collects and uses your personal information to operate its website(s) and deliver the services you have requested.</p>
 
<p>Scout may also use your personally identifiable information to inform you of other products or services available from Scout and its affiliates. Scout may also contact you via surveys to conduct research about your opinion of current services or of potential new services that may be offered. </p>
 
<h3>Scout does not sell, rent or lease its customer lists to third parties.</h3>
 
<p>Scout may share data with trusted partners to help perform statistical analysis, send you email or postal mail, provide customer support, or arrange for deliveries. All such third parties are prohibited from using your personal information except to provide these services to Scout, and they are required to maintain the confidentiality of your information.</p>
 
<p>Scout may keep track of the websites and pages our users visit within Scout, in order to determine what Scout services are the most popular. This data is used to deliver customized content and advertising within Scout to customers whose behavior indicates that they are interested in a particular subject area.</p>
 
<p>Scout will disclose your personal information, without notice, only if required to do so by law or in the good faith belief that such action is necessary to: (a) conform to the edicts of the law or comply with legal process served on Scout or the site; (b) protect and defend the rights or property of Scout; and, (c) act under exigent circumstances to protect the personal safety of users of Scout, or the public.</p>
 
<h3>Use of Cookies</h3>
<p>The Scout website may use "cookies" to help you personalize your online experience. A cookie is a text file that is placed on your hard disk by a web page server. Cookies cannot be used to run programs or deliver viruses to your computer. Cookies are uniquely assigned to you, and can only be read by a web server in the domain that issued the cookie to you.</p>
 
<p>One of the primary purposes of cookies is to provide a convenience feature to save you time. The purpose of a cookie is to tell the Web server that you have returned to a specific page. For example, if you personalize Scout pages, or register with Scout site or services, a cookie helps Scout to recall your specific information on subsequent visits. This simplifies the process of recording your personal information, such as billing addresses, shipping addresses, and so on. When you return to the same Scout website, the information you previously provided can be retrieved, so you can easily use the Scout features that you customized. </p>
 
<p>You have the ability to accept or decline cookies. Most Web browsers automatically accept cookies, but you can usually modify your browser setting to decline cookies if you prefer. If you choose to decline cookies, you may not be able to fully experience the interactive features of the Scout services or websites you visit.</p>
 
<h3>Security of your Personal Information</h3>
 
<p>Scout secures your personal information from unauthorized access, use or disclosure. When personal information (such as a credit card number) is transmitted to other websites, it is protected through the use of encryption, such as the Secure Sockets Layer (SSL) protocol.</p>
 
 
<h3>Children Under Thirteen</h3>
<p>Scout does not knowingly collect personally identifiable information from children under the age of thirteen. If you are under the age of thirteen, you must ask your parent or guardian for permission to use this website.</p>
 
<h3>Disconnecting your Scout Account from Third Party Websites</h3>
<p>You will be able to connect your Scout account to third party accounts. BY CONNECTING YOUR SCOUT ACCOUNT TO YOUR THIRD PARTY ACCOUNT, YOU ACKNOWLEDGE AND AGREE THAT YOU ARE CONSENTING TO THE CONTINUOUS RELEASE OF INFORMATION ABOUT YOU TO OTHERS (IN ACCORDANCE WITH YOUR PRIVACY SETTINGS ON THOSE THIRD PARTY SITES). IF YOU DO NOT WANT INFORMATION ABOUT YOU, INCLUDING PERSONALLY IDENTIFYING INFORMATION, TO BE SHARED INTHIS MANNER, DO NOT USE THE THIS FEATURE. You may disconnect your account from a third party account at any time. User's may disconnect their account directly from Facebook by going to Apps, Settings and then by removing Scout.</p>
 
<h3>Opt-Out & Unsubscribe </h3>
<p>We respect your privacy and give you an opportunity to opt-out of receiving announcements of certain information. Users may opt-out of receiving any or all communications from Scout by contacting us here:
Email: info@meet-scout.herokupp.com</p>
 
<h3>Changes to this Statement </h3>
<p>Scout will occasionally update this Statement of Privacy to reflect company and customer feedback. Scout encourages you to periodically review this Statement to be informed of how Scout is protecting your information. </p>
 
<h3>Contact Information</h3>
<p>Scout welcomes your questions or comments regarding this Statement of Privacy. If you believe that Scout has not adhered to this Statement, please contact Scout at:</p>
 
<p>Scout.com
1935 N. Rainbow Blvd #1935
Las Vegas, Nevada 89107
 
Email Address:
info@meet-scout.herokuapp.com
   
Effective as of December 09, 2016 </p>
</div>